version: '3.8'
services:
  bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    restart: unless-stopped
