version: '3.8'  # Use the correct version of Docker Compose

services:
  bot:  # Service name
    build: .  # Build the Docker image from the current directory
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}  # Environment variable
    restart: unless-stopped  # Automatically restart the container if it stops
